[package]
name = "centrevo-analysis"
version = "0.2.1"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[dependencies]
centrevo-sim = { path = "../sim" }
nalgebra = "0.33"
statrs = "0.18"
rayon = "1.10"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
